# Introduction

Got client data for 3 seasons (2015, 2016, 2017)
- Geographic data = Region, District, Site
- Groupint/Ops data = Site, GroupName, Facilitator
- Transaction Data = TXsize, %Repaid, LastRepayDate

## Objective
- Do summary stats and graphs with Py 
    - Sample structure 
    - Key outcomes summary stats = Group/Site size, Transaction Size, % repaid, % group complete, % individual complete, Outstanding amounts, 
    - Distribution graphs 
    - Correlation matrix for key outcomes 
    - Analysis levels = individual, Facilitator, group, site, district, region 
    
    
- Try clustering/classification/segmentation
    - Facilitator?
    - Group Size
    - TXsize, 
    - % repaid
    - Outstanding amount, Overpayment amount
    
    
- Account time series
    - 3 seasons
    - last repayment date

In [202]:
### Setup

## 1. Load Libraries
import pandas as pd
import numpy as np
import seaborn as sns

%matplotlib inline 

## 2. Load def fxs
df_name_prefix = "df_sc"
df_cols = ["xClientID", "xSiteID", "xPodID", "xGroupID",
           "Year",
           "RegionName", "DistrictName", 
          "Facilitator", 
           "TotalCredit", "TotalRepaid_IncludingOverpayments", "LastRepaymentDate"]

def load_csv(yr, fprefix, dsdir):
    print( " WORKING on PATH : %s/%s_%d.csv" %(dsdir,fprefix,yr)  )
    dtmp = pd.read_csv( "%s/%s_%d.csv" %(dsdir,fprefix,yr) )
    dtmp["Year"] = yr
    dtmp["xClientID"] = str(yr) + "_"+dtmp.GlobalClientId 
    dtmp["xSiteID"] = str(yr) + "_"+dtmp.SiteName 
    dtmp["xPodID"] = str(yr) + "_"+dtmp.SectorName
    dtmp["xGroupID"] = str(yr) + "_"+dtmp.GroupName 
    dtmp.index = dtmp.xClientID
    print( "LOADED df " )
    return dtmp[df_cols] 
    

def computed_fields(df):
    df["PctRepaid"] =  np.minimum( 1, df.TotalRepaid_IncludingOverpayments/df.TotalCredit )
    df["OverpaymentAmt"] = np.maximum(0, df.TotalRepaid_IncludingOverpayments - df.TotalCredit)
    df["OutstandingAmt"] = np.maximum(0, df.TotalCredit - df.TotalRepaid_IncludingOverpayments )
    df.rename(columns={"TotalCredit":"TXSize", "TotalRepaid_IncludingOverpayments":"TotalRepaid"}, inplace=True)

## Agg level outcomes = group size, [sum,mean](totalcredit, totalrepaid, outstanding, overpayment), %repaid 
def group_aggz( grplvl, holding_dict ):
    df = all_data.groupby([ grplvl ]).agg({
        "xClientID" : ["size"],
        "PctRepaid" : ["mean"],
        "TXSize" : ["mean", "sum"],
        "TotalRepaid" : ["mean", "sum"],
        "OutstandingAmt" : ["mean", "sum"],
        "OverpaymentAmt" : ["mean", "sum"],
    })
    
    # df flatten multi-index cols 

    holding_dict[grplvl] = df
    
    return None
    
    
    
## 3. Define key outcomes 
outcomes = ["TXSize", "PctRepaid", "OutstandingAmt", "OverpaymentAmt", ]


## 4. Load dataset 
data_dir = "D:/xAppzor/datasets/oaf"
data_file_prefix = "oaf_sc"
seasons = [2015, 2016, 2017]


all_data = pd.concat(  np.asarray(
    pd.Series( seasons ).apply(
        lambda x: load_csv(x, data_file_prefix, data_dir) ) 
) )



## 5. Computed Fields
computed_fields( all_data )

print("\n\n all data = \n" , all_data.info() , "\nIndecies\n", all_data.index.names,
     "\n\n Sample", all_data[ all_data.TotalRepaid != all_data.TXSize][ outcomes ].sample(7),
      "\n\n CFO\n", all_data.groupby(["xSiteID"]).size()
     )



## 6. Aggregates = group size, [sum,mean](totalcredit, totalrepaid, outstanding, overpayment), %repaid
# grouping levels = site, pod, group
grp_levels = ["xSiteID", "xPodID", "xGroupID"] 
aggz_data = {} 

pd.Series( grp_levels ).apply( lambda x:  group_aggz(x, aggz_data) ) 

aggz_data["xGroupID"].head()
#site_data.head()

 WORKING on PATH : D:/xAppzor/datasets/oaf/oaf_sc_2015.csv
LOADED df
 WORKING on PATH : D:/xAppzor/datasets/oaf/oaf_sc_2016.csv
LOADED df
 WORKING on PATH : D:/xAppzor/datasets/oaf/oaf_sc_2017.csv
LOADED df

C:\Users\wairimu\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in minimum

<class 'pandas.core.frame.DataFrame'>
Index: 578840 entries, 2015_60608205-6fba-4932-a022-511006e668c5 to 2017_24205200-f191-e611-9e9a-2c600c86e73a
Data columns (total 14 columns):
xClientID            578840 non-null object
xSiteID              578840 non-null object
xPodID               578840 non-null object
xGroupID             578840 non-null object
Year                 578840 non-null int64
RegionName           578840 non-null object
DistrictName         578840 non-null object
Facilitator          578840 non-null bool
TXSize               578840 non-null float64
TotalRepaid          578840 non-null float64
LastRepaymentDate    578837 non-null object
PctRepaid            578838 non-null float64
OverpaymentAmt       578840 non-null float64
OutstandingAmt       578840 non-null float64
dtypes: bool(1), float64(5), int64(1), object(7)
memory usage: 62.4+ MB


 all data =
 None
Indecies
 ['xClientID']

 Sample                                             TXSize  PctRepaid  OutstandingAmt  \
xClientID
2017_0b5c1869-8496-e611-bc82-201a06e9340a   8375.0   1.000000             0.0
2017_b924e0c8-8478-e511-ab82-90489a3eb024  13535.0   0.893979          1435.0
2017_f1c0ff86-aa78-e511-b75a-ace0107446f8  11025.0   0.967800           355.0
2017_33c7952e-26a0-e611-97fc-2c600c86ea95   8590.0   0.570431          3690.0
2017_6cac15f9-0e8a-e611-ad41-ace0107446f8   5675.0   1.000000             0.0
2017_1e41e898-e78a-e611-9874-d85de236908e   4585.0   0.817884           835.0
2017_09b6b194-838f-e611-904b-f8a96372641d   3885.0   0.626512          1451.0

                                           OverpaymentAmt
xClientID
2017_0b5c1869-8496-e611-bc82-201a06e9340a            25.0
2017_b924e0c8-8478-e511-ab82-90489a3eb024             0.0
2017_f1c0ff86-aa78-e511-b75a-ace0107446f8             0.0
2017_33c7952e-26a0-e611-97fc-2c600c86ea95             0.0
2017_6cac15f9-0e8a-e611-ad41-ace0107446f8             5.0
2017_1e41e898-e78a-e611-9874-d85de236908e             0.0
2017_09b6b194-838f-e611-904b-f8a96372641d             0.0

 CFO
 xSiteID
2015_Aboke               150
2015_Aboloi              163
2015_Achuth              235
2015_Aedomoru            176
2015_Akobwait            186
2015_Aloette             244
2015_Alomodoi            219
2015_Alungoli            103
2015_Amukura             291
2015_Anjego              324
2015_Anyiko              193
2015_Apondo              117
2015_Asayi               220
2015_Atemo               174
2015_Aterait             167
2015_BIGEGE              117
2015_BOGETENGA           136
2015_BOKIMAI             108
2015_BONYAGWANGA         100
2015_BONYAIGUBA          150
2015_BOOCHI              102
2015_BOSINANGE           142
2015_BOTABORI BOMWARE    110
2015_BUYONGE             103
2015_Bar Sauri           163
2015_Baraki              153
2015_Bisunu              130
2015_Bitobo              179
2015_Bituyu              210
2015_Block Ten           241
                        ...
2017_Uhuyi               306
2017_Ulafu               228
2017_Ulumba              422
2017_Umala               334
2017_Upper Dudi          140
2017_UpperKowili         157
2017_Uranga              226
2017_Uriri               208
2017_Uyundo              335
2017_Victorious          122
2017_Vigulu              325
2017_Vinyenya            144
2017_Virhembe            138
2017_Wabukhonyi          166
2017_Wagai East          341
2017_Waitaluk            126
2017_Wakhungu            331
2017_Walodeya            190
2017_Wambulishe          207
2017_Wamono              132
2017_Wasio               150
2017_Wasweta 1           149
2017_Weonia              205
2017_Westkarachuonyo     164
2017_Wiga                109
2017_Yiro West           322
2017_kingandole          216
2017_lusiola             172
2017_mabonde             121
2017_masara              107
Length: 2832, dtype: int64

              xClientID PctRepaid        TXSize             TotalRepaid  \
                   size      mean          mean       sum          mean
xGroupID
2015_ Mkulima         9       1.0  10687.777778   96190.0  10687.777778
2015_A to Z          14       1.0  12449.285714  174290.0  12449.285714
2015_AGAPE            7       1.0   9098.571429   63690.0   9098.571429
2015_ALALA WG         8       1.0   9866.250000   78930.0   9866.250000
2015_AMANI            9       1.0  10372.222222   93350.0  10372.222222

                        OutstandingAmt      OverpaymentAmt
                    sum           mean  sum           mean  sum
xGroupID
2015_ Mkulima   96190.0            0.0  0.0            0.0  0.0
2015_A to Z    174290.0            0.0  0.0            0.0  0.0
2015_AGAPE      63690.0            0.0  0.0            0.0  0.0
2015_ALALA WG   78930.0            0.0  0.0            0.0  0.0
2015_AMANI      93350.0            0.0  0.0            0.0  0.0

# Individual Level Analysis

## Data Structure
- GlobalID=Index Unique, 
- TXsize, Total repaid including overpayment 
- % repaid, OutstandingAmt, OverpaymentAmt